apiVersion: batch/v1
kind: CronJob
metadata:
  name: mortgage-rate-scraper
  labels:
    app.kubernetes.io/instance: refinance-scraper
spec:
  schedule: "0 */24 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: public.ecr.aws/b7c8g1g5/linuxeclipsed/refinancescraper:25.02.19
            env:
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: morgage-secrets
                  key: token
            - name: INFLUXDB_ORG
              valueFrom:
                secretKeyRef:
                  name: morgage-secrets
                  key: org
            - name: INFLUXDB_URL
              valueFrom:
                secretKeyRef:
                  name: morgage-secrets
                  key: url
            - name: INFLUXDB_BUCKET
              value: "mortgage_rates"
            - name: ZILLOW_PID
              valueFrom:
                secretKeyRef:
                  name: morgage-secrets
                  key: pid
          restartPolicy: OnFailure