apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  namespace: ai
  labels:
    app: whisper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whisper
  template:
    metadata:
      labels:
        app: whisper
    spec:
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Equal"
        value: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu
                operator: In
                values:
                  - "true"
      containers:
      - name: whisper
        image: lscr.io/linuxserver/faster-whisper:gpu
        ports:
        - containerPort: 10300
        env:
        - name: WHISPER_MODEL
          value: tiny-int8
        - name: WHISPER_LANG
          value: en
        resources:
          limits:
            nvidia.com/gpu: 1