apiVersion: v1
kind: Service
metadata:
  name: whisper
  namespace: ai
spec:
  type: NodePort
  selector:
    app: whisper
  ports:
  - port: 10300
    targetPort: 10300
    protocol: TCP
    nodePort: 32626