apiVersion: v1
kind: ConfigMap
metadata:
    name: prometheus-configmap
    namespace: prometheus
    labels:
        app: prometheus
data:
    prometheus.yml: |
        global:
          scrape_interval: 15s

        scrape_configs:
        - job_name: node
          static_configs:
          - targets: ['192.168.2.250:9100']
