apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-db-data
  namespace: "prometheus"
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/k8s/prometheus/db
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-db-pvc
  namespace: "prometheus"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: prometheus-db-data
  resources:
    requests:
      storage: 2Gi