apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeprojectai-ingress
  namespace: codeprojectai
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - codeprojectai.local.koryalbert.net
    secretName: koryalbert-tls
  rules:
  - host: codeprojectai.local.koryalbert.net
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codeproject-ai
                port:
                  number: 32168