apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data-pvc
  namespace: uptime-kuma
spec:
  storageClassName: longhorn
  volumeName: uptime-kuma-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi