apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redisdata
  namespace: paperless
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-db-pvc
  namespace: paperless
spec:
  storageClassName: longhorn
  volumeName: paperless-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data-pvc
  namespace: paperless
spec:
  storageClassName: longhorn
  volumeName: paperless-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi