apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.1
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "700m"
              memory: "300Mi"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: speedtest
                  key: dbpass
            - name: POSTGRES_DB
              value: speedtest_tracker
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: speedtest
                  key: dbuser
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: speedtest-db-pvc
