apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auburntech
  annotations:
    kubernetes.io/change-cause: "Updated rollout & probes"
  name: auburntech
  namespace: auburntech-dmz
spec:
  selector:
    matchLabels:
      app: auburntech
  strategy:
    type: RollingUpdate
    rollingUpdate:
     maxUnavailable: 0
     maxSurge: 2
  template:
    metadata:
      labels:
        app: auburntech
    spec:
      containers:
        - name: auburntech
          image: trafex/php-nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: website-port
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: website-port
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              path: /
              port: website-port
            initialDelaySeconds: 5
            failureThreshold: 30
            periodSeconds: 5
          resources:
            requests:
              cpu: 20m
              memory: 40Mi
            limits:
              cpu: 100m
              memory: 150Mi
          volumeMounts:
            - mountPath: /var/www/html
              name: auburntech-data
      volumes:
        - name: auburntech-data
          persistentVolumeClaim:
            claimName: auburntech-pvc