apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auburntech
  namespace: auburntech-dmz

spec:
  ingressClassName: nginx
  rules:
  - host: auburntechconsulting.com
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auburntech
                port:
                  number: 8080
  - host: www.auburntechconsulting.com
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: auburntech
                port:
                  number: 8080