apiVersion: v1
kind: PersistentVolume
metadata:
  name: auburntech-data
  namespace: auburntech-dmz
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/k8s/auburntech
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auburntech-pvc
  namespace: auburntech-dmz
spec:
  storageClassName: local-path
  volumeName: auburntech-data
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi