apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-data-pvc
  namespace: arr
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi