apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cookbook
  namespace: cookbook
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - cookbook.local.koryalbert.net
    secretName: koryalbert-tls
  rules:
  - host: cookbook.local.koryalbert.net
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cookbook-web
                port:
                  number: 80