apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellystat
  name: jellystat
spec:
  ports:
    - port: 3000
  selector:
    app: jellystat
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jellystat-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: jellystat-db
  type: ClusterIP