apiVersion: v1
kind: PersistentVolume
metadata:
  name: cookbook-db-data
  namespace: "cookbook"
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/k8s/cookbook/db
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cookbook-data
  namespace: "cookbook"
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/k8s/cookbook/app
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cookbook-db-pvc
  namespace: "cookbook"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: cookbook-db-data
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cookbook-app-pvc
  namespace: "cookbook"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: cookbook-data
  resources:
    requests:
      storage: 1Gi