apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db-pvc
  namespace: "nextcloud-dmz"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: nextcloud-db
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
  namespace: "nextcloud-dmz"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: nextcloud-app
  resources:
    requests:
      storage: 2Gi