apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-redis-data
  namespace: "authentik-dmz"
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/k8s/authentik/redis
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentik-postgres-data
  namespace: "authentik-dmz"
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /mnt/k8s/authentik/postgres
  nodeAffinity:
    required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: "authentik-dmz"
  labels:
    app.kubernetes.io/instance: authentik
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: master
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-path
  volumeName: authentik-redis-data
  resources:
    requests:
      storage: "8Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: "authentik-dmz"
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-path
  volumeName: authentik-postgres-data
  resources:
    requests:
      storage: "8Gi"